### ISSUE TITLE
Detect and report #[no_mangle]

### ISSUE THREAD

**Issue by Nemo157** [rust-secure-code/cargo-geiger#104]
Running this program results in a segfault, because using `#[no_mangle]` to override C functions can be UB (see also https://github.com/rust-lang/rust/issues/28179)

```rust
#![forbid(unsafe_code)]

#[no_mangle]
fn write() {
    panic!("wat");
}

fn main() {
    println!("Hello, world!");
}
```

```
11:12 → RUST_BACKTRACE=short cargo run
   Compiling foo v0.1.0 (/tmp/tmp.kxF5z55SRc/foo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.28s
     Running `target/debug/foo`
[1]    1501355 segmentation fault (core dumped)  RUST_BACKTRACE=short cargo run
```

But `cargo-geiger` marks this crate as being `unsafe` free

```
0/0        0/0          0/0    0/0     0/0      :) foo 0.1.0
```

**Comment by anderejd** [comment]
Thanks for opening this issue. The linked github issue was an interesting read and I agree that cargo-geiger should probably try to find #[no_mangle].

**Comment by kornelski** [comment]
I'd like to voice my support for this.

`cargo-crev` tries to flag crates that use unsafe features (unsafe in a broad sense, not by Rust's own strict definition), and `#[no_mangle]` is an undetected loophole.

**Comment by anderejd** [comment]
This should be relatively easy to add support for. The main work will be in https://github.com/rust-secure-code/cargo-geiger/blob/master/geiger/src/lib.rs

It will still be easy to intentionally hide usage of no_mangle (and unsafe), since we don't have #102 yet, resulting in shenanigans like #101.

This task is a great first issue, so anyone who's feeling tempted to contribute, feel free to jump right in! :) I'm currently in minimal effort mode when it comes to open source projects and will probably be doing release and dependency upgrades but not much else for the foreseeable future.
