### ISSUE TITLE
panic in .toml parser on some repos

### ISSUE THREAD

**Issue by emilk** [rust-secure-code/cargo-geiger#83]
Version: `cargo-geiger 0.9.0`

```
$ cargo geiger
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:1165:5
stack backtrace:
...
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: cargo::util::canonical_url::CanonicalUrl::new
  16: cargo::core::source::source_id::SourceId::new
  17: cargo::util::toml::DetailedTomlDependency::to_dependency
  18: cargo::util::toml::TomlDependency::to_dependency
  19: cargo::util::toml::TomlManifest::to_real_manifest::process_dependencies
  20: cargo::util::toml::TomlManifest::to_real_manifest
  21: cargo::util::toml::read_manifest
  22: cargo::core::workspace::Packages::load
  23: cargo::core::workspace::Workspace::find_root
  24: cargo::core::workspace::Workspace::new
  25: cargo_geiger::cli::get_workspace
  26: cargo_geiger::main
  27: std::rt::lang_start::{{closure}}
  28: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  29: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  30: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  31: std::panicking::try
             at src/libstd/panicking.rs:265
  32: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  33: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  34: main
  35: __libc_start_main
  36: _start
```

it would be useful to get at least the line number in the `.toml` file that causes the problem.

**EDIT:** I tried eliminating lines in my `Cargo.toml` to find the offending code, but even with my whole `Cargo.toml` commented I got the above error. Weird. `geiger` works fine in some other repos.

**Comment by anderejd** [comment]
Thank you for the error report!

I'm guessing there's some new feature in cargo 0.41 that is needed to parse these files. My time is super limited at the moment, would you mind trying updating the cargo dependency to the latest version running the same test again?

**Comment by emilk** [comment]
On latest `master` of `cargo-geiger` I get a better error message: "couldn't get the path to cargo executable". I am trying to run `cargo-geiger` on a workspace with multiple subcrates and binaries. Running it on a subcrate with just one binary still results in the above error message.

Relevant stacktrace:

```
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:933
  16: cargo_geiger::cli::run_scan_mode_default
             at cargo-geiger/src/cli.rs:276
  17: cargo_geiger::real_main
             at cargo-geiger/src/main.rs:319
  18: cargo_geiger::main
             at cargo-geiger/src/main.rs:341
```

I attempted updating the cargo dependency (https://github.com/anderejd/cargo-geiger/pull/85) yet I still get the same error.

**Comment by anderejd** [comment]
Can you provide a minimal example project that reproduce the error?

**Comment by emilk** [comment]
What is the best way to approach that task? I just discovered that changing `Cargo.toml` and re-running `cargo geiger` does nothing if I don't also delete the `Cargo.lock` file. It took me way too long to discover that :/

**Comment by anderejd** [comment]
> What is the best way to approach that task? 

I'm guessing that you have a private that you can't share, but if that assumption is incorrect and you can share the problematic project, that would be perfect. To create a minimal example would involve spending time to remove things piece by piece , one dependency and related code at a time, until the error goes away and then go back one step and try to remove other dependencies. So probably quite time consuming and I don't expect you to have that time, but it would be helpful to find this specific error.

> I just discovered that changing Cargo.toml and re-running cargo geiger does nothing if I don't also delete the Cargo.lock file. It took me way too long to discover that :/

This is probably expected behavior from the cargo library. The lock file is expected to override the Cargo.toml, as far as I know.

**Comment by Shnatsel** [comment]
If I change Cargo.toml and then run `cargo build`, the Cargo.lock file will be automatically discarded and regenerated. I'd expect the same from running `cargo geiger`.

**Comment by anderejd** [comment]
This sounds like new issue, created one here: #91

**Comment by emilk** [comment]
I think the problem might be having a dependency on a private repo:

`some_crate = { git = "ssh://git@github.com/secret/private.git", rev = "765dad2a94394c1f9b27a001ab1f0d301ab1f0d3" }`

**Comment by pinkforest** [comment]
Different errors here, 

No reproduction anymore sadly (?) as of today - 

The errors today are pretty verbose and I never hit the situation with panic and stack trace on my face.

We've bumped interfaces and cargo (to 0.58.0) quite a bit so it's quite different situation compared to a year ago

Also more important a lot of the panics / error messages have been cleaned up back in end of February that touched metadata stuff

The errors are now quite informative - a lot of it coming from cargo metadata

Will close and re-open if this can be reproduced and we can define the underlying issue if there is still one.

Thanks for the effort :purple_heart:

**Comment by pinkforest** [comment]
I think I found the exact code in Cargo where this failed.

Cargo util did this
`cargo::util::canonical_url::CanonicalUrl::new`

CanonicalUrl in turn uses url::Url

**Cargo today - 0.58.0 or latest - does not panic anymore with Git Urls**
https://docs.rs/cargo/latest/src/cargo/util/canonical_url.rs.html

Doing a bit digging -

They were working around https://github.com/servo/rust-url/issues/577 under PR https://github.com/rust-lang/cargo/pull/7787

Someone else noticed this error as well
https://github.com/xd009642/tarpaulin/issues/319

There is quite bit of unwrap() and the underlying dep url :: set_scheme changed behaviour between 2.1.0 and 2.1.1
https://github.com/servo/rust-url/issues/577#issue-547714982

The unwrap() on cargo can be found that panic()'s
https://docs.rs/cargo/0.41.0/src/cargo/util/canonical_url.rs.html#42

Canonical_url.rs was originally added on
```
Commit e54541225142b509f5f3b7468897b2c31a7635dc
Date:   Mon Sep 16 12:35:03 2019 -0700
```

However..

I suspect it is because Url::url::set_scheme() 2.1.1 introduced a new Err that was not handled in Cargo/canonical_url.rs
https://docs.rs/url/2.1.0/src/url/lib.rs.html#1978-2008
https://docs.rs/url/2.1.1/src/url/lib.rs.html#2055-2104

So what did Cargo do? Well they removed Url::url::set_scheme and replaced it with 
`url = format!("https{}", &url[url::Position::AfterScheme..])

Change here showing removal of set_scheme that was suddenly returning Err for unwrap() causing the panic on Git URL:
https://docs.rs/cargo/0.41.0/src/cargo/util/canonical_url.rs.html#42
https://docs.rs/cargo/latest/src/cargo/util/canonical_url.rs.html#42`

And this was worked around in Cargo 0.43.0 - sadly it did not end up in Cargo 0.42.0
https://docs.rs/cargo/0.43.0/src/cargo/util/canonical_url.rs.html#42

Tracing the commit where it was fixed
```
Commit dde27346685e09166967616581aac383918b2c04
Date:   Fri Jan 10 08:00:35 2020 -0800

    Fix tests with `url` crate update
    
    Works around servo/rust-url#577

diff --git a/src/cargo/util/canonical_url.rs b/src/cargo/util/canonical_url.rs
index 37060bd54..c6f305279 100644
--- a/src/cargo/util/canonical_url.rs
+++ b/src/cargo/util/canonical_url.rs
@@ -39,7 +39,9 @@ impl CanonicalUrl {
         // almost certainly not using the same case conversion rules that GitHub
         // does. (See issue #84)
         if url.host_str() == Some("github.com") {
-            url.set_scheme("https").unwrap();
+            url = format!("https{}", &url[url::Position::AfterScheme..])
+                .parse()
+                .unwrap();
             let path = url.path().to_lowercase();
             url.set_path(&path);
         }

```

**Comment by pinkforest** [comment]
Future reminder to myself:

I need to go thru ecosystem the amount of Err(()) and then try to cross-map unwrap() calls to potential Err(())'s
And if there are tons of references to stuff that Err's and then unwrap() somewhere on library level it might be valuable to keep track of list of this kind to reduce confusing panic() across the ecosystem and give visibility to devs as to amount of potential panic that can be caused with changes.
